import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const dialogs = [
  { slug: "connexion", description: "Connexion — page d'accueil publique", imageName: "m1.png", actif: true, bulles: [{"text":"Saisissez l'adresse e-mail et le mot de passe de votre espace. Si votre maison d'édition dispose d'une adresse dédiée, vous pouvez aussi passer par elle directement.","title":"Bienvenue 👋"},{"text":"Après dix tentatives infructueuses en une minute, l'accès se bloque quelques instants. C'est une protection contre les robots qui essaient des mots de passe au hasard — patientez une minute et réessayez."},{"cta":{"href":"/mot-de-passe-oublie","label":"Réinitialiser mon mot de passe →"},"text":"Mot de passe égaré ? Nous vous envoyons un lien par e-mail, valable une heure."}] },
  { slug: "mot-de-passe-oublie", description: "Connexion — page mot de passe oublie", imageName: "m3.png", actif: true, bulles: [{"text":"Indiquez l'adresse e-mail de votre compte : nous vous envoyons un lien pour choisir un nouveau mot de passe. Il est valable une heure, et ne peut servir qu'une seule fois.","title":"Pas de panique 🔑"},{"text":"Par sécurité, le message de confirmation est le même que votre adresse soit connue ou non. Cela évite qu'un curieux puisse deviner quels comptes existent chez nous."},{"text":"Rien ne s'affiche dans votre boîte au bout de quelques minutes ? Regardez vos indésirables, et vérifiez l'orthographe de l'adresse saisie."}] },
  { slug: "reinitialiser-mot-de-passe", description: "Connexion — choix du nouveau mot de passe", imageName: "m5.png", actif: true, bulles: [{"text":"Choisissez un mot de passe d'au moins 8 caractères, puis saisissez-le une seconde fois pour éviter la faute de frappe.","title":"Votre nouveau mot de passe ✍️"},{"text":"Un conseil qui vaut pour tous vos comptes : une phrase que vous seul retenez vaut mieux qu'un mot compliqué. « MonChatDortSurLeClavier » est plus solide et plus facile à retenir que « X7f!2q »."},{"text":"Une fois validé, votre ancien mot de passe cesse immédiatement de fonctionner, et le lien reçu par e-mail devient inutilisable."}] },
  { slug: "aide-auteur-quota", description: "Catalogue - Bouton quota", imageName: "m2.png", actif: true, bulles: [{"text":"C'est ici que MeGesti t'indique la place qu'il nous reste sur les rayons ! Cet indicateur te montre tes articles en vente par rapport à ce que permet ton abonnement."},{"text":"Tes étagères sont pleines ? Pas de souci ! Déplace quelques titres vers 'Retirés' pour libérer de la place. Les articles hors catalogue ne comptent pas dans ton quota."},{"text":"Et si tu te sens encore à l'étroit, tu peux passer au Plan Édition Pro. Là, c'est open-bar : on pousse les murs et il n'y a plus aucune limite !"}] },
  { slug: "aide-auteur-switch", description: "Auteur - Bouton d'aide pour le switch ME/Réseau", imageName: "m2.png", actif: true, bulles: [{"text":"Besoin d'un coup de main pour t'y retrouver ? C'est tout simple !"},{"text":"Côté Auteurs ME, tu trouveras ton équipe officielle : ceux qui ont un contrat actif avec ta maison d'édition et pour qui MeGesti calcule les droits d'auteur automatiquement."},{"text":"Et côté Réseau, c'est ton carnet d'adresses perso ! Ajoute ici tes contacts et futurs talents pour garder un œil sur ton réseau pro."}] },
  { slug: "aide-catalogue-switch", description: "Catalogue - Explique la différence entre En catalogue et Retirés", imageName: "m2.png", actif: true, bulles: [{"text":"Ici, c'est le cœur de ta boutique ! Dans En catalogue, tu gères tout ce qui est prêt à être vendu depuis la caisse de la plateforme MeGesti comme depuis l'application compagnon (ton app mobile préféré)."},{"text":"Un livre n'est plus édité ? Un produit est épuisé ? Bascule-le dans Retirés. Il disparaîtra des ventes instantanément, comme par magie !"},{"text":"Et pas de panique : si tu décides de le rééditer, tu peux le ressortir des archives en un clic. Rien n'est jamais perdu ici !"}] },
  { slug: "aide-pdv-categorie", description: "Point de Vente - Catégorie", imageName: "m1.png", actif: true, bulles: [{"text":"Ici, on met de l'ordre ! Ajoute ou modifie tes catégories pour regrouper tes lieux de vente par style"},{"text":"Bibliothèques, Centres Culturels, Salons... Classer tes points de vente, c'est l'astuce magique pour t'y retrouver en un clin d'œil dans quelques mois."},{"text":"Tu peux en créer autant que tu veux. C'est toi qui décides du rangement !"}] },
  { slug: "aide-ventespage-historique", description: "Caisse - Switch Caisse/historique", imageName: "m2.png", actif: true, bulles: [{"text":"Le switch est simple : à gauche la Caisse pour vendre et gérer tes sessions de vente actuelles. On enregistre tout ici !"},{"text":"À droite l'Historique pour voir tes archives de sessions closes. C'est ici que tu analyses tes succès ! L'Historique, c'est ta mine d'or pour savoir exactement quel titre a fait craquer les lecteurs sur chaque événement."},{"text":"Bref, le présent d'un côté, tes victoires de l'autre."}] },
  { slug: "aide-ventespage-switch", description: "Caisse - aide pour le bouton vente hors session", imageName: "m2.png", actif: true, bulles: [{"text":"Un voisin t'arrête alors que tu sors les poubelles pour t'acheter ton dernier livre ? Pas besoin d'ouvrir une session officielle pour ça !"},{"text":"Le bouton 'Vente hors session', c'est pour ces ventes imprévues, à l'unité, quand tu n'es ni en salon ni en dédicace."},{"text":"C'est rapide, c'est propre, et ça garde ta compta à jour même quand tu es en pyjama !"}] },
  { slug: "auteurs-vide", description: "Auteurs — aucun auteur enregistré (switch ME ou Réseau)", imageName: "m1.png", actif: true, bulles: [{"text":"Cette page regroupe tous les auteurs avec qui tu travailles ou que tu suis. C'est le point de départ pour gérer les contrats, calculer les droits et piloter tes reversements — tout ce qui touche à la relation auteur.","title":"Tes auteurs, centralisés ici ✍️"},{"text":"📂 L'onglet Réseau te donne accès à la base partagée d'auteurs référencés sur MeGesti — utile pour retrouver un auteur déjà enregistré par une autre maison, éviter les doublons et enrichir automatiquement les fiches.\n\n👥 L'onglet ME liste les auteurs directement rattachés à ta maison d'édition, avec leurs contrats, leurs œuvres et le calcul de leurs droits."},{"cta":{"href":"","label":"Ajouter mon premier auteur →"},"text":"💡 Les auteurs ME — avec gestion de contrats et calcul automatique des droits — sont disponibles à partir du plan Édition. En plan Auto-édition, tu peux consulter le Réseau et importer des auteurs, mais la gestion contractuelle est réservée aux structures qui publient plusieurs auteurs."}] },
  { slug: "bilan-metric-benefice", description: "Bilan — bénéfice estimé", imageName: "m1.png", actif: true, bulles: [{"text":"Calcul indicatif : chiffre d'affaires hors taxe − coût des ventes − frais de session − commission PDV − droits d'auteurs. Uniquement calculé si les prix d'achat sont renseignés sur les articles. Il ne s'agit pas d'un résultat comptable certifié.","title":"Bénéfice estimé hors taxe"}] },
  { slug: "bilan-metric-ca-ttc", description: "Bilan — chiffre d'affaires total", imageName: "m1.png", actif: true, bulles: [{"text":"Somme de toutes les ventes validées de cette session, toutes taxes comprises. Le montant hors taxe affiché dessous sert de base au calcul de la TVA et des droits d'auteurs.","title":"Chiffre d'affaires total"}] },
  { slug: "bilan-metric-commission-pdv", description: "Bilan — commission du point de vente", imageName: "m1.png", actif: true, bulles: [{"text":"Frais prélevés par le point de vente partenaire sur les ventes qu'il encaisse pour toi. Il peut être forfaitaire (montant fixe) ou proportionnel (pourcentage du chiffre d'affaires encaissé par le PDV).\n\nCe montant est déduit du bénéfice estimé affiché dans ce bilan.","title":"Commission du point de vente"}] },
  { slug: "bilan-metric-cout-ventes", description: "Bilan — coût des ventes", imageName: "m1.png", actif: true, bulles: [{"text":"Estimation du coût d'achat des articles vendus, calculée à partir du prix d'achat unitaire renseigné sur chaque article. Sert à estimer la marge brute. Affiché uniquement si au moins un article a un prix d'achat configuré.","title":"Coût des ventes"}] },
  { slug: "bilan-metric-droits", description: "Bilan — droits d'auteurs", imageName: "m1.png", actif: true, bulles: [{"text":"Total des droits dus aux auteurs pour les ventes de cette session, calculé selon les barèmes de leurs contrats (pourcentage du hors taxe ou du toutes taxes comprises, avec déduction des à-valoirs déjà versés). Ce montant est à reverser aux auteurs concernés.","title":"Droits d'auteurs"}] },
  { slug: "bilan-metric-en-caisse", description: "Bilan — montant encaissé directement", imageName: "m1.png", actif: true, bulles: [{"text":"Part du chiffre d'affaires que tu as encaissée toi-même (carte, espèces, chèque…). Le montant « + X € PDV » correspond aux ventes réglées par le point de vente partenaire — il te sera reversé selon les modalités convenues.","title":"Montant encaissé directement"}] },
  { slug: "bilan-metric-frais", description: "Bilan — frais de session", imageName: "m1.png", actif: true, bulles: [{"text":"Total des dépenses liées à cette session : stand, déplacement, repas, hébergement… Déduits du bénéfice estimé mais sans impact sur le chiffre d'affaires. Les frais annulés (rayés) ne sont pas comptabilisés.","title":"Frais de session"}] },
  { slug: "bilan-metric-ticket-moyen", description: "Bilan — ticket moyen", imageName: "m1.png", actif: true, bulles: [{"text":"Chiffre d'affaires total ÷ nombre de ventes validées. Un bon indicateur pour évaluer si les clients achètent plusieurs articles ou un seul à chaque passage.","title":"Ticket moyen"}] },
  { slug: "bilan-no-data", description: "Bilan — aucune donnée disponible", imageName: "m1.png", actif: true, bulles: [{"text":"C'est ta boussole comptable. En un seul regard, tu vois la santé financière réelle de ta maison d'édition : ce que tu as vendu, encaissé, dépensé — et surtout ce qu'il te reste vraiment.","title":"Ton bilan financier 💼"},{"text":"Tu suis tes entrées (ventes en session, dépôts libraires, reversements PDV…) et tes sorties (frais de salon, droits d'auteurs versés, charges, coût des ventes…) avec un comparatif effectif vs prévisionnel pour anticiper sans jamais être surpris."},{"text":"Au programme : un compte de résultat simplifié du CA au résultat net, une estimation de la valeur de ton stock, et des alertes sur les charges à venir pour piloter ta trésorerie en temps réel."},{"cta":{"href":"/ventes","label":"Aller à la Caisse →"},"text":"Pour que tout s'affiche, il te faut au moins une session de caisse clôturée avec des ventes enregistrées. Lance ta première session et reviens ici — les chiffres t'en apprendront plus sur ton activité que n'importe quel tableur !"}] },
  { slug: "caisse-no-active", description: "Caisse — sessions passées mais aucune ouverte", imageName: "m1.png", actif: true, bulles: [{"cta":{"href":"","label":"Ouvrir une session →"},"text":"Ouvre une session pour démarrer une journée de vente dans un point de vente. Pour une vente rapide et isolée, utilise le bouton Vente hors session en haut de page.","title":"Prêt à reprendre ? 👋"}] },
  { slug: "caisse-no-pdv", description: "Caisse — aucun point de vente", imageName: "m1.png", actif: true, bulles: [{"text":"C'est ici que tu centralises toutes tes ventes — lors d'un salon, d'une expo, en boutique ou ponctuellement. Chaque euro encaissé passe par ici.","title":"Bienvenue dans la Caisse ! 🏪"},{"cta":{"href":"/points-de-vente","label":"Créer mon premier point de vente →"},"text":"Avant de commencer à vendre, il te faut au moins un Point de vente — le lieu où se déroulera ta vente. Tu peux en créer autant que tu veux et avoir plusieurs sessions actives simultanément."}] },
  { slug: "caisse-premiere-session", description: "Caisse — PDV OK mais jamais de session", imageName: "m1.png", actif: true, bulles: [{"text":"Pour enregistrer des ventes, deux modes s'offrent à toi :","title":"Tout est en place ! 🎉"},{"text":"📦 La session — tu l'ouvres au début d'une journée de vente, tu enregistres tous tes clients au fil de la journée, puis tu la fermes en fin de journée. Idéal pour un salon, une expo, un marché. Plusieurs sessions peuvent tourner en même temps."},{"cta":{"href":"","label":"Ouvrir ma première session →"},"text":"⚡ La vente hors session — pour le coup ponctuel et rapide : un lecteur te contacte directement, tu enregistres sa commande en deux clics, sans ouvrir de session."}] },
  { slug: "catalogue-lien-rayons", description: "Catalogue — rappel discret vers réglages rayons/catégories", imageName: "m1.png", actif: true, bulles: [{"cta":{"href":"/reglages","label":"Réglages → Rayons & Catégories"},"text":"Rayons, catégories, TVA, champs personnalisés… tout se configure dans les Réglages."}] },
  { slug: "catalogue-no-article", description: "Catalogue — rayons OK mais aucun article", imageName: "m1.png", actif: true, bulles: [{"cta":{"href":"","label":"Ajouter mon premier article"},"text":"Ton catalogue est prêt. Ajoute maintenant ton premier article — livre, goodie, affiche… tout ce que tu vends !","title":"C'est parti ! 🎉"},{"text":"L'onglet Catalogue affiche tous les produits actuellement disponibles à la vente. C'est la vitrine active de ta maison d'édition."},{"text":"L'onglet Retirés accueille les articles mis de côté. Ils ne sont plus en vente mais ne sont pas supprimés — tu peux les réactiver à tout moment."}] },
  { slug: "catalogue-no-rayon", description: "Catalogue — aucun rayon créé", imageName: "m1.png", actif: true, bulles: [{"text":"Avant d'ajouter ton premier article, crée au moins un rayon et une catégorie pour structurer ton catalogue.","title":"Par ici ! 👋"},{"cta":{"href":"/reglages","label":"Réglages → Rayons & Catégories →"},"text":"Rends-toi dans les Réglages pour organiser ton catalogue en rayons (Librairie, Goodies…) puis en catégories."}] },
  { slug: "catalogue-retires-vide", description: "Catalogue / onglet Retirés — aucun article retiré", imageName: "m1.png", actif: true, bulles: [{"text":"Cet espace accueille les articles que vous avez mis de côté — produits épuisés, éditions terminées, références que vous ne souhaitez plus proposer pour l'instant.\n\nUne fois retirés, ils disparaissent de la caisse, de l'application mobile, et ne sont plus proposés à la vente.","title":"Vos articles retirés atterrissent ici 📦"},{"text":"Ils ne disparaissent pas de vos statistiques ni de votre historique de ventes — votre bilan reste intact. Et ils ne consomment plus de crédits dans votre quota d'articles actifs."},{"text":"Un article retiré peut être réintégré en un seul clic : il revient immédiatement dans l'onglet Catalogue et redevient disponible à la vente. Aucune donnée n'est perdue."}] },
  { slug: "depots-vide", description: "Dépôts libraires — aucun dépôt enregistré", imageName: "m1.png", actif: true, bulles: [{"text":"Tu confies des exemplaires de tes livres à une librairie partenaire — elle les expose, les vend pour toi à ton prix public, et te reverse ta part selon une commission convenue. C'est le dépôt-vente : tu restes propriétaire des livres jusqu'à leur vente, aucun intermédiaire ne te les rachète.","title":"Tes dépôts en librairie 📚"},{"text":"Pour chaque dépôt, MeGesti suit les quantités envoyées, les quantités vendues et ce qu'il reste en rayon. Fini les calculs sur un coin de nappe : tu sais à tout moment ce que chaque librairie te doit."},{"cta":{"href":"","label":"Référencer ma première librairie →"},"text":"Quand la librairie te verse ta part, enregistre le reversement ici. MeGesti met à jour le solde et conserve l'historique — précieux pour ta comptabilité et tes relations partenaires."}] },
  { slug: "facturation-pdp-non-configure", description: "Facturation — identifiants superpdp manquants", imageName: "m1.png", actif: true, bulles: [{"text":"Pour émettre des factures électroniques, renseignez vos identifiants superpdp.tech dans les réglages de votre compte (section Facturation électronique).","title":"Configuration requise"},{"cta":{"href":"/reglages","label":"Réglages → Facturation"},"text":"Il vous faut un compte sur superpdp.tech avec une application créée pour votre entreprise. L'opération prend 5 minutes."}] },
  { slug: "facturation-quota-epuise", description: "Facturation — quota mensuel épuisé, proposition de rechargement", imageName: "m1.png", actif: true, bulles: [{"text":"Vous avez utilisé toutes vos factures du mois. Pas de panique : rechargez votre facturier en un clic et continuez à émettre sans interruption.","title":"Notre facturier est vide !"},{"cta":{"href":"","label":"Recharger mon facturier →"},"text":"Le rechargement est immédiat. Vos factures sont disponibles dès la confirmation du paiement."}] },
  { slug: "maisons-vide", description: "Maisons d'édition — aucune entrée", imageName: "m1.png", actif: true, bulles: [{"text":"Ici, tu recenses les maisons d'édition partenaires ou celles que tu surveilles — concurrentes, complémentaires, coéditrices potentielles… C'est la mémoire de ton réseau professionnel éditorial.\n\nEt pourquoi pas y noter la maison d'édition qui te fait de l'œil… ou celle qui pourrait bien te faire signe un jour ? 😉","title":"Ton carnet de maisons d'édition ! 📚"},{"text":"Pour chaque maison, tu notes ses contacts clés, son adresse, son site, ses spécialités… Plus besoin de chercher un numéro de téléphone en plein salon quand on n'a pas le temps."},{"cta":{"href":"","label":"Ajouter une maison d'édition →"},"text":"Ce carnet prend de la valeur avec le temps. Un bon réseau éditorial ouvre des portes : coéditions, co-stands en salon, échanges de bons procédés, recommandations croisées… Commence dès maintenant."}] },
  { slug: "pdv-no-categorie", description: "Points de vente — aucune catégorie", imageName: "m1.png", actif: true, bulles: [{"text":"Un point de vente est un lieu ou canal où tu vends tes produits — un stand en salon, une librairie partenaire, ta boutique… Chaque PDV a ses propres sessions, statistiques et mode d'encaissement.","title":"Les points de vente, c'est quoi ? 🏪"},{"cta":{"href":"","label":"Créer ma première catégorie →"},"text":"Pour s'y retrouver, MeGesti organise tes points de vente en catégories — Salon littéraire, Librairie indépendante, Centre culturel… C'est toi qui les définis. Commence par créer ta première catégorie."}] },
  { slug: "pdv-no-pdv", description: "Points de vente — catégorie OK mais aucun PDV", imageName: "m1.png", actif: true, bulles: [{"text":"Maintenant, ajoute ton premier point de vente. MeGesti saura ainsi où se sont déroulées tes ventes et pourra te donner des statistiques par lieu.","title":"La première catégorie est là ! 🎉"},{"cta":{"href":"","label":"Ajouter mon premier point de vente →"},"text":"💡 Lors de la création, choisis le mode d'encaissement :\n🏪 Tu encaisses toi-même (CB, espèces, chèque…)\n🏬 Le point de vente encaisse et te reverse ensuite ta part."}] },
  { slug: "reglages-fiscal", description: "Réglages / Paramètres fiscaux — mascotte permanente sidebar", imageName: "m1.png", actif: true, bulles: [{"text":"Ce réglage indique à MeGesti comment traiter fiscalement vos ventes. C'est l'un des paramètres les plus importants — mal configuré, vos prix et exports comptables seraient faux.","title":"TVA : le bon régime dès le départ 🧾"},{"text":"🟢 Franchise en base de TVA — si vous êtes micro-entreprise ou auto-entrepreneur sous le seuil légal (~91 900 € de CA annuel), vous n'avez ni à collecter ni à reverser la TVA. Vos prix HT = prix TTC. MeGesti applique automatiquement la mention légale obligatoire : « TVA non applicable, art. 293 B du CGI »."},{"text":"🔵 Assujetti à la TVA — si vous avez dépassé le seuil ou opté pour un statut avec TVA (SARL, SAS…), vous collectez la TVA sur vos ventes et la reversez à l'administration. MeGesti applique alors les taux configurés par rayon (5,5 % livres, 20 % autres)."},{"text":"💡 Une fois configuré selon votre statut, vous n'aurez plus à y toucher — sauf en cas de changement de situation : franchissement du seuil, transformation juridique, ou option volontaire pour la TVA. En dehors de ces cas, oubliez ce réglage, MeGesti s'en occupe."}] },
  { slug: "reglages-rayons-pret", description: "Réglages / Rayons — sidebar, tout configuré (rappel)", imageName: "m1.png", actif: true, bulles: [{"text":"Pour ajouter un nouveau rayon, utilise le bouton Nouveau rayon. Clique sur + dans un rayon pour y ajouter des catégories.","title":"Rappel rapide 💡"},{"text":"N'oublie pas d'activer le mode Librairie sur tes rayons qui vendent des livres — la TVA et les champs spécifiques se configurent automatiquement."}] },
  { slug: "reglages-rayons-sans-categories", description: "Réglages / Rayons — sidebar, rayon(s) créé(s) sans catégorie", imageName: "m1.png", actif: true, bulles: [{"text":"Clique sur le + dans l'en-tête du rayon pour y ajouter des catégories. Les catégories permettent de classer tes articles plus finement.","title":"Super, ton premier rayon ! 🎉"},{"text":"Ce rayon vend des livres ? Clique sur l'icône livre dans l'en-tête pour activer le mode Librairie — TVA 5,5 % + ISBN + auteurs activés automatiquement."},{"text":"Ajuste la TVA de chaque rayon manuellement en cliquant sur son badge TVA x % dans l'en-tête."}] },
  { slug: "reglages-rayons-vide", description: "Réglages / Rayons — sidebar, aucun rayon créé", imageName: "m1.png", actif: true, bulles: [{"text":"Le catalogue est organisé en rayons puis en catégories. Exemple : Librairie → Romans, BD, Jeunesse…","title":"Comment ça marche ? 🗂️"},{"cta":{"href":"","label":"Créer mon premier rayon"},"text":"Commence par créer ton premier rayon. Les catégories et articles s'ajouteront ensuite !"}] },
  { slug: "salons-vide", description: "Salons — aucun salon enregistré", imageName: "m1.png", actif: true, bulles: [{"text":"Ici, tu références tous les salons et événements qui t'intéressent — salons du livre, festivals, marchés… Passés ou à venir, garde-les tous ici pour construire ton calendrier annuel.","title":"Ton carnet de salons ! 📅"},{"text":"Pour chaque salon : les dates et le lieu, les coordonnées de l'organisateur, le coût du stand… Et surtout, MeGesti conserve le CA des éditions précédentes pour t'aider à décider si l'événement vaut le déplacement."},{"cta":{"href":"","label":"Référencer mon premier salon →"},"text":"Depuis la fiche d'un salon, tu peux créer directement un Point de vente associé. Tes sessions de caisse seront automatiquement liées au salon, sans ressaisie."}] },
  { slug: "stats-no-data", description: "Statistiques — aucune vente sur la période", imageName: "m1.png", actif: true, bulles: [{"text":"C'est ici que se trouvent tes performances commerciales en un coup d'œil : chiffre d'affaires, progression dans le temps, articles les plus vendus et les plus rentables, points de vente les plus performants, modes de paiement préférés de tes clients… tout est centralisé.","title":"Tes statistiques de ventes 📊"},{"text":"Tu peux filtrer par période — 7 jours, 30 jours, 3 mois, un an ou depuis le tout début — pour suivre tes tendances, comparer tes résultats d'un salon à l'autre et identifier tes bestsellers."},{"cta":{"href":"/ventes","label":"Aller à la Caisse →"},"text":"Pour que les données apparaissent, il te faut au moins une session de caisse clôturée avec des ventes enregistrées. Si tu viens de changer la période, essaie d'élargir l'intervalle !"}] }
]


async function main() {
  let created = 0
  let skipped = 0
  for (const d of dialogs) {
    const existing = await prisma.mascoteDialog.findUnique({ where: { slug: d.slug } })
    if (!existing) {
      await prisma.mascoteDialog.create({
        data: { slug: d.slug, description: d.description, bulles: d.bulles as any },
      })
      created++
    } else {
      skipped++
    }
  }
  console.log(`✓ Dialogs MeGestine : ${created} créés, ${skipped} déjà présents`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
