import type { FastifyPluginAsync } from 'fastify'
import { authRoutes }      from './auth.js'
import { thesaurusRoutes } from './thesaurus.js'
import { customFieldRoutes }      from './custom-fields.js'
import { customFieldValueRoutes } from './custom-field-values.js'
import { auteurRoutes }                   from './auteurs.js'
import { maisonEditionRoutes }            from './maisons-edition.js'
import { depotLibraireRoutes }            from './depots-libraires.js'
import { salonRoutes }                    from './salons.js'
import { categoriePointDeVenteRoutes }    from './categories-point-de-vente.js'
import { pointDeVenteRoutes }             from './points-de-vente.js'
import { sessionCaisseRoutes }            from './sessions-caisse.js'
import { venteRoutes }                    from './ventes.js'
import { rayonRoutes }     from './rayons.js'
import { categorieRoutes } from './categories.js'
import { articleRoutes }   from './articles.js'
import { dashboardRoutes }     from './dashboard.js'
import { typeSalonRoutes }      from './types-salon.js'
import { typeDARoutes }         from './types-da.js'
import { contratAuteurRoutes }  from './contrats-auteur.js'
import { imprimeurRoutes }       from './imprimeurs.js'
import { rapportRoutes }         from './rapports.js'
import { mouvementStockRoutes }  from './mouvements-stock.js'
import { fraisRoutes }           from './frais.js'
import { reversementRoutes }     from './reversements.js'
import { monTenantRoutes }       from './mon-tenant.js'
import { chargeRoutes }          from './charges.js'
import { motifVenteRoutes }      from './motifs-vente.js'
import { droitsAuteurRoutes }    from './droits-auteur.js'
import { contactsTenantRoutes }  from './contacts-tenant.js'
import { mascoteDialogRoutes }   from './mascote-dialogs.js'
import { popupRoutes }           from './popups.js'
import { facturationRoutes }     from './facturation.js'
import { stripeRoutes }          from './stripe.js'

export const routes: FastifyPluginAsync = async (app) => {
  await app.register(authRoutes,        { prefix: '/auth' })
  await app.register(thesaurusRoutes,   { prefix: '/thesauri' })
  await app.register(customFieldRoutes,      { prefix: '/custom-fields' })
  await app.register(customFieldValueRoutes, { prefix: '/custom-field-values' })
  await app.register(auteurRoutes,                   { prefix: '/auteurs' })
  await app.register(maisonEditionRoutes,            { prefix: '/maisons-edition' })
  await app.register(depotLibraireRoutes,            { prefix: '/depots-libraires' })
  await app.register(salonRoutes,                    { prefix: '/salons' })
  await app.register(categoriePointDeVenteRoutes,    { prefix: '/categories-point-de-vente' })
  await app.register(pointDeVenteRoutes,             { prefix: '/points-de-vente' })
  await app.register(sessionCaisseRoutes,            { prefix: '/sessions-caisse' })
  await app.register(venteRoutes,                    { prefix: '/ventes' })
  await app.register(rayonRoutes,       { prefix: '/rayons' })
  await app.register(categorieRoutes,   { prefix: '/categories' })
  await app.register(articleRoutes,     { prefix: '/articles' })
  await app.register(dashboardRoutes,    { prefix: '/dashboard' })
  await app.register(typeSalonRoutes,    { prefix: '/types-salon' })
  await app.register(typeDARoutes,       { prefix: '/types-da' })
  await app.register(contratAuteurRoutes, { prefix: '/contrats-auteur' })
  await app.register(imprimeurRoutes,     { prefix: '/imprimeurs' })
  await app.register(rapportRoutes,       { prefix: '/rapports' })
  await app.register(mouvementStockRoutes, { prefix: '/mouvements-stock' })
  await app.register(fraisRoutes,          { prefix: '/frais' })
  await app.register(reversementRoutes,    { prefix: '/reversements' })
  await app.register(monTenantRoutes,      { prefix: '/mon-tenant' })
  await app.register(chargeRoutes,         { prefix: '/charges' })
  await app.register(motifVenteRoutes,     { prefix: '/motifs-vente' })
  await app.register(droitsAuteurRoutes,   { prefix: '/droits-auteur' })
  await app.register(contactsTenantRoutes, { prefix: '/contacts-tenant' })
  await app.register(mascoteDialogRoutes,  { prefix: '/mascote-dialogs' })
  await app.register(popupRoutes,          { prefix: '/popups' })
  await app.register(facturationRoutes,    { prefix: '/facturation' })
  await app.register(stripeRoutes,         { prefix: '/stripe' })
}
